title = "DeriveLinux Ports"
description = "THE LAST PUNK DISTRO"
footer_text = "The DeriveLinux Quality Larping Center"
source_code_url = "https://codeberg.org/derivelinux/ports"

# Paths
ports_path = "./ports"
out_dir = "./public"
cache_dir = "./.cache"
assets_dir = "./assets"

# Runtime
port = 8080
verbose = true
serve = false
watch = false

# Assets Configuration
extra_css = ["styles.css"]
extra_js = ["search.js", "commits.js", "fortunes.js"]
fortunes = "fortunes.txt"

[metadata]
ci_status = "./ci-pkgs/ci_status.json"
pkg_root = "./ci-pkgs/pkg"
log_root = "./ci-pkgs/logs"
